cargo-features = ["panic-immediate-abort"]

[workspace]
resolver = "2"
members = ["wllib", "rustbg", "rustemp", "rustidle", "rustclip", "rust-randr"]

[profile.dev]
panic = "immediate-abort"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
debug = "none"
strip = true
panic = "immediate-abort"
